"use client";
import { useEffect, useState } from 'react';
import { invoiceApi, Invoice } from '@/lib/api';
import { useParams } from 'next/navigation';
import { toast } from 'react-hot-toast';
import { format } from 'date-fns';

export default function PrintableInvoicePage() {
  const params = useParams();
  const id = params?.id as string;
  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [downloading, setDownloading] = useState(false);

  const load = async () => {
    try {
      if (!id) return;
      const data = await invoiceApi.getById(Number(id));
      setInvoice(data);
    } catch (e:any) {
      toast.error('Failed to load invoice');
    }
  };

  useEffect(()=>{ load(); }, [id]);

  const downloadPdf = async () => {
    if (!id) return;
    setDownloading(true);
    try {
      const blob = await invoiceApi.downloadPdf(id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `invoice_${invoice?.invoice_number || id}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (e:any) {
      toast.error('PDF download failed');
    } finally {
      setDownloading(false);
    }
  };

  if (!invoice) return <div className="p-6">Loading...</div>;

  return (
    <div className="p-8 print:p-0 max-w-3xl mx-auto bg-white shadow print:shadow-none">
      <div className="flex justify-between items-start mb-8 print:mb-4">
        <div>
          <h1 className="text-2xl font-semibold mb-1">Invoice</h1>
          <p className="text-sm text-gray-600">Invoice #: {invoice.invoice_number}</p>
          <p className="text-sm text-gray-600">Date: {format(new Date(invoice.created_at), 'dd MMM yyyy')}</p>
        </div>
        <div className="text-right">
          <button onClick={()=>window.print()} className="btn btn-primary mr-2 hidden print:hidden">Print</button>
          <button onClick={downloadPdf} disabled={downloading} className="btn btn-primary hidden print:hidden disabled:opacity-50">
            {downloading ? 'Downloading...' : 'PDF'}
          </button>
        </div>
      </div>

      <div className="mb-8 grid grid-cols-2 gap-6 print:gap-4">
        <div>
          <h2 className="font-medium mb-2">Bill To</h2>
          <p className="font-medium">{invoice.customer_name}</p>
          <p className="text-sm text-gray-600">{invoice.customer_phone}</p>
          {invoice.customer_email && <p className="text-sm text-gray-600">{invoice.customer_email}</p>}
        </div>
        <div>
          <h2 className="font-medium mb-2">Summary</h2>
          <p className="text-sm text-gray-600">Status: {invoice.status}</p>
          <p className="text-sm text-gray-600">GST Rate: {invoice.gst_rate}%</p>
        </div>
      </div>

      <table className="w-full text-sm mb-8">
        <thead>
          <tr className="border-b">
            <th className="py-2 text-left">Service Type</th>
            <th className="py-2 text-left">Description</th>
            <th className="py-2 text-right">Amount</th>
            <th className="py-2 text-right">GST</th>
            <th className="py-2 text-right">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b">
            <td className="py-2 align-top font-medium">{invoice.service_type}</td>
            <td className="py-2 align-top max-w-sm">{invoice.service_description}</td>
            <td className="py-2 text-right">₹{invoice.amount.toLocaleString()}</td>
            <td className="py-2 text-right">₹{invoice.gst_amount.toLocaleString()}</td>
            <td className="py-2 text-right font-medium">₹{invoice.total_amount.toLocaleString()}</td>
          </tr>
        </tbody>
      </table>

      <div className="flex justify-end mb-12 print:mb-4">
        <div className="w-64">
          <div className="flex justify-between py-1 text-sm">
            <span>Subtotal</span>
            <span>₹{invoice.amount.toLocaleString()}</span>
          </div>
          <div className="flex justify-between py-1 text-sm">
            <span>GST ({invoice.gst_rate}%)</span>
            <span>₹{invoice.gst_amount.toLocaleString()}</span>
          </div>
          <div className="flex justify-between py-1 text-sm font-medium border-t mt-2 pt-2">
            <span>Total</span>
            <span>₹{invoice.total_amount.toLocaleString()}</span>
          </div>
        </div>
      </div>

      <p className="text-xs text-gray-500 print:mt-8">Thank you for your business. This invoice was generated by the GST Service Center Management System.</p>
    </div>
  );
}
